### ISSUE TITLE
When writing root files in "develop," stan_write_root() thinks it takes 3 arguments

### ISSUE THREAD

**Issue by taliaweiss** [project8/morpho#23]
I am running a morpho model using the "develop" branch version of morpho. When I try to write a root file, I get the error, "stan_write_root() takes exactly 3 arguments (4 given)." When I open pystanLoad.py, stan_write_root() clearly takes 4 arguments: it is defined in line 240, "def stan_write_root(conf, theFileName, theOutput, input_param):" However, when I ask morpho.py to print out the arguments of stan_write_root(), it prints, args=['conf', 'theFileName', 'theOutput'].

@guiguem – Is this happening for you?

**Comment by laroque** [comment]
Don't know anything abuot morpho, but that error message seems likely to indicate that the version of the file being used isn't the one you're editing. Perhaps you should redo `python setup.py develop` (or install, if that's what you use in your development cycle). Remember that `install` will copy the current version of your source files (changes won't show up until the next install), and `develop` will make symbolic links, so changes pass automatically (for better or for worse).

**Comment by taliaweiss** [comment]
Hi Ben – thanks very much. I found a different version of the file and got rid of it, then re-did `python setup.py develop,` but the problem persists. I'll keep working on this and may end up creating a new virtualenv to work in if I can't resolve it.

**Comment by guiguem** [comment]
Very weird. Unfortunately I could not reproduce this problem with the develop branch and using the morph_test example in the morpho repo...
This error might be because of the changes I have done over the last days in the develop branch
I would recommend you to recreate your virtualenv (and reinstall everything) or you could try to use the version before (by checking out a previous version and ```python setup.py install```; maybe version e4b1ab1 which corresponds to your addition of the automatic cache/results creation).
I don't know which is best, the first should just work: you can try the morph_test example. If it does not work with a clean virtual environment, this will be a big problem.

**Comment by taliaweiss** [comment]
I made a new virtualenv, cloned morpho, installed requirements, and installed morpho, and the problem is solved! Thanks for the help.
