### ISSUE TITLE
Seed problem

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#6]
When starting a Stan MC calculation, I have the following warning:
/usr/local/lib/python2.7/site-packages/pystan/misc.py:632: UserWarning: `seed` must be castable to an integer
  warnings.warn("`seed` must be castable to an integer")

**Comment by taliaweiss** [comment]
I believe that this is occurring because we took out the seed specification in the __init__ function of morpho.py, for the purpose of being able to run batch jobs on the engaging cluster (where Joe and I are running morpho) in which each chain would have a different seed. (The chains are divided up between a number of nodes, and if a seed is specified in __init__, every chain will begin in the same location.) I am not certain what effect the seed not being "castable to an integer" has – but if you would like to temporarily circumvent this bug, you can add back in a seed in morpho.py, e.g. "self.seed = self.read_param(yd, 'stan.run.seed', '314159')"

**Comment by guiguem** [comment]
Yes sure! I tried to modify the "self.seed = self.read_param(yd, 'stan.run.seed', '')" to "self.seed = self.read_param(yd, 'stan.run.seed', None)". And this error did not appear. That might be the fix I was looking for.

**Comment by guiguem** [comment]
A follow-up: the seed with the --autoseed argument uses the python random library based on the current time of the machine. Submitting jobs at different times should really randomize the seeds.
